export const BOARD = [
  {
    hidden: true,
    label: "",
    notes: [
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: null, marker: null },
    ],
  },
  {
    label: "e",
    notes: [
      { active: false, value: "F", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "G", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "A", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "B", marker: null },
      { active: false, value: "C", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "D", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "E", marker: null },
    ],
  },
  {
    label: "B",
    notes: [
      { active: false, value: "C", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "D", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "E", marker: null },
      { active: false, value: "F", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "G", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "A", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "B", marker: null },
    ],
  },
  {
    label: "G",
    notes: [
      { active: false, value: null, marker: null },
      { active: false, value: "A", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "B", marker: null },
      { active: false, value: "C", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "D", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "E", marker: null },
      { active: false, value: "F", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "G", marker: true },
    ],
  },
  {
    label: "D",
    notes: [
      { active: false, value: null, marker: null },
      { active: false, value: "E", marker: null },
      { active: false, value: "F", marker: true },
      { active: false, value: null, marker: null },
      { active: false, value: "G", marker: true },
      { active: false, value: null, marker: null },
      { active: false, value: "A", marker: true },
      { active: false, value: null, marker: null },
      { active: false, value: "B", marker: true },
      { active: false, value: "C", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "D", marker: null },
    ],
  },
  {
    label: "A",
    notes: [
      { active: false, value: null, marker: null },
      { active: false, value: "B", marker: null },
      { active: false, value: "C", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "D", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "E", marker: null },
      { active: false, value: "F", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "G", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "A", marker: true },
    ],
  },
  {
    hidden: true,
    label: "E",
    notes: [
      { active: false, value: "F", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "G", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "A", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "B", marker: null },
      { active: false, value: "C", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "D", marker: null },
      { active: false, value: null, marker: null },
      { active: false, value: "E", marker: null },
    ],
  },
];
