export const resetBoard = () => {
  return [
    {
      label: "e",
      notes: [
        { active: false, value: "F" },
        { active: false, value: null },
        { active: false, value: "G" },
        { active: false, value: null },
        { active: false, value: "A" },
        { active: false, value: null },
        { active: false, value: "B" },
        { active: false, value: "C" },
        { active: false, value: null },
        { active: false, value: "D" },
        { active: false, value: null },
        { active: false, value: "E" },
      ],
    },
    {
      label: "B",
      notes: [
        { active: false, value: "C" },
        { active: false, value: null },
        { active: false, value: "D" },
        { active: false, value: null },
        { active: false, value: "E" },
        { active: false, value: "F" },
        { active: false, value: null },
        { active: false, value: "G" },
        { active: false, value: null },
        { active: false, value: "A" },
        { active: false, value: null },
        { active: false, value: "B" },
      ],
    },
    {
      label: "G",
      notes: [
        { active: false, value: null },
        { active: false, value: "E" },
        { active: false, value: "F" },
        { active: false, value: null },
        { active: false, value: "G" },
        { active: false, value: null },
        { active: false, value: "A" },
        { active: false, value: null },
        { active: false, value: "B" },
        { active: false, value: "C" },
        { active: false, value: null },
        { active: false, value: "D" },
      ],
    },
    {
      label: "D",
      notes: [
        { active: false, value: null },
        { active: false, value: "E" },
        { active: false, value: "F" },
        { active: false, value: null },
        { active: false, value: "G" },
        { active: false, value: null },
        { active: false, value: "A" },
        { active: false, value: null },
        { active: false, value: "B" },
        { active: false, value: "C" },
        { active: false, value: null },
        { active: false, value: "D" },
      ],
    },
    {
      label: "A",
      notes: [
        { active: false, value: null },
        { active: false, value: "B" },
        { active: false, value: "C" },
        { active: false, value: null },
        { active: false, value: "D" },
        { active: false, value: null },
        { active: false, value: "E" },
        { active: false, value: "F" },
        { active: false, value: null },
        { active: false, value: "G" },
        { active: false, value: null },
        { active: false, value: "A" },
      ],
    },
    {
      hidden: true,
      label: "E",
      notes: [
        { active: false, value: "F" },
        { active: false, value: null },
        { active: false, value: "G" },
        { active: false, value: null },
        { active: false, value: "A" },
        { active: false, value: null },
        { active: false, value: "B" },
        { active: false, value: "C" },
        { active: false, value: null },
        { active: false, value: "D" },
        { active: false, value: null },
        { active: false, value: "E" },
      ],
    },
  ];
};
